/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as ChatRouteImport } from './app/chat'
import { Route as AuthPathRouteImport } from './app/auth/$path'
import { Route as ChatChatIdRouteImport } from './app/chat/$chatId'
import { Route as ChatroomSectionRouteImport } from './app/chatroom/$section'
import { Route as GatewayIndexRouteImport } from './app/gateway/index'
import { Route as GatewaySectionRouteImport } from './app/gateway/$section'
import { Route as GatewayTelemetryRouteImport } from './app/gateway/telemetry'
import { Route as SettingsPathRouteImport } from './app/settings/$path'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as ApiChatgptSubscriptionSplatRouteImport } from './app/api/chatgpt-subscription/$'
import { Route as GatewayTelemetryIdRouteImport } from './app/gateway/telemetry/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatroomSectionRoute = ChatroomSectionRouteImport.update({
  id: '/chatroom/$section',
  path: '/chatroom/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayIndexRoute = GatewayIndexRouteImport.update({
  id: '/gateway/',
  path: '/gateway/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaySectionRoute = GatewaySectionRouteImport.update({
  id: '/gateway/$section',
  path: '/gateway/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayTelemetryRoute = GatewayTelemetryRouteImport.update({
  id: '/gateway/telemetry',
  path: '/gateway/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPathRoute = SettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptSubscriptionSplatRoute =
  ApiChatgptSubscriptionSplatRouteImport.update({
    id: '/api/chatgpt-subscription/$',
    path: '/api/chatgpt-subscription/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const GatewayTelemetryIdRoute = GatewayTelemetryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GatewayTelemetryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatroom/$section': typeof ChatroomSectionRoute
  '/gateway/$section': typeof GatewaySectionRoute
  '/gateway/telemetry': typeof GatewayTelemetryRouteWithChildren
  '/settings/$path': typeof SettingsPathRoute
  '/gateway/': typeof GatewayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chatgpt-subscription/$': typeof ApiChatgptSubscriptionSplatRoute
  '/gateway/telemetry/$id': typeof GatewayTelemetryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatroom/$section': typeof ChatroomSectionRoute
  '/gateway/$section': typeof GatewaySectionRoute
  '/gateway/telemetry': typeof GatewayTelemetryRouteWithChildren
  '/settings/$path': typeof SettingsPathRoute
  '/gateway': typeof GatewayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chatgpt-subscription/$': typeof ApiChatgptSubscriptionSplatRoute
  '/gateway/telemetry/$id': typeof GatewayTelemetryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatroom/$section': typeof ChatroomSectionRoute
  '/gateway/$section': typeof GatewaySectionRoute
  '/gateway/telemetry': typeof GatewayTelemetryRouteWithChildren
  '/settings/$path': typeof SettingsPathRoute
  '/gateway/': typeof GatewayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chatgpt-subscription/$': typeof ApiChatgptSubscriptionSplatRoute
  '/gateway/telemetry/$id': typeof GatewayTelemetryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/auth/$path'
    | '/chat/$chatId'
    | '/chatroom/$section'
    | '/gateway/$section'
    | '/gateway/telemetry'
    | '/settings/$path'
    | '/gateway/'
    | '/api/auth/$'
    | '/api/chatgpt-subscription/$'
    | '/gateway/telemetry/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/auth/$path'
    | '/chat/$chatId'
    | '/chatroom/$section'
    | '/gateway/$section'
    | '/gateway/telemetry'
    | '/settings/$path'
    | '/gateway'
    | '/api/auth/$'
    | '/api/chatgpt-subscription/$'
    | '/gateway/telemetry/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/auth/$path'
    | '/chat/$chatId'
    | '/chatroom/$section'
    | '/gateway/$section'
    | '/gateway/telemetry'
    | '/settings/$path'
    | '/gateway/'
    | '/api/auth/$'
    | '/api/chatgpt-subscription/$'
    | '/gateway/telemetry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
  ChatroomSectionRoute: typeof ChatroomSectionRoute
  GatewaySectionRoute: typeof GatewaySectionRoute
  GatewayTelemetryRoute: typeof GatewayTelemetryRouteWithChildren
  SettingsPathRoute: typeof SettingsPathRoute
  GatewayIndexRoute: typeof GatewayIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatgptSubscriptionSplatRoute: typeof ApiChatgptSubscriptionSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chatroom/$section': {
      id: '/chatroom/$section'
      path: '/chatroom/$section'
      fullPath: '/chatroom/$section'
      preLoaderRoute: typeof ChatroomSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/': {
      id: '/gateway/'
      path: '/gateway'
      fullPath: '/gateway/'
      preLoaderRoute: typeof GatewayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/$section': {
      id: '/gateway/$section'
      path: '/gateway/$section'
      fullPath: '/gateway/$section'
      preLoaderRoute: typeof GatewaySectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/telemetry': {
      id: '/gateway/telemetry'
      path: '/gateway/telemetry'
      fullPath: '/gateway/telemetry'
      preLoaderRoute: typeof GatewayTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$path': {
      id: '/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof SettingsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt-subscription/$': {
      id: '/api/chatgpt-subscription/$'
      path: '/api/chatgpt-subscription/$'
      fullPath: '/api/chatgpt-subscription/$'
      preLoaderRoute: typeof ApiChatgptSubscriptionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/telemetry/$id': {
      id: '/gateway/telemetry/$id'
      path: '/$id'
      fullPath: '/gateway/telemetry/$id'
      preLoaderRoute: typeof GatewayTelemetryIdRouteImport
      parentRoute: typeof GatewayTelemetryRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface GatewayTelemetryRouteChildren {
  GatewayTelemetryIdRoute: typeof GatewayTelemetryIdRoute
}

const GatewayTelemetryRouteChildren: GatewayTelemetryRouteChildren = {
  GatewayTelemetryIdRoute: GatewayTelemetryIdRoute,
}

const GatewayTelemetryRouteWithChildren =
  GatewayTelemetryRoute._addFileChildren(GatewayTelemetryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  AuthPathRoute: AuthPathRoute,
  ChatroomSectionRoute: ChatroomSectionRoute,
  GatewaySectionRoute: GatewaySectionRoute,
  GatewayTelemetryRoute: GatewayTelemetryRouteWithChildren,
  SettingsPathRoute: SettingsPathRoute,
  GatewayIndexRoute: GatewayIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatgptSubscriptionSplatRoute: ApiChatgptSubscriptionSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
